name: delivery_partner
description: Delivery Platform partner app.
publish_to: none
version: 1.0.3+4
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  flutter_secure_storage: ^9.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

