'use strict';
const $=id=>document.getElementById(id), key='delivery-handoff-demo-v1';
let order=null;
try{order=JSON.parse(localStorage.getItem(key))}catch{}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const say=(message,error=false)=>{$('message').textContent=message;$('message').className=error?'error':'notice'};
function view(name){document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==name);document.querySelectorAll('[data-view]').forEach(el=>el.setAttribute('aria-selected',String(el.dataset.view===name)))}
document.querySelectorAll('[data-view]').forEach(el=>el.addEventListener('click',()=>view(el.dataset.view)));
$('file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(file.size>1024*1024){say('Choose a JSON file under 1 MB.',true);return}try{$('cart').value=await file.text();JSON.parse($('cart').value);say('Cart JSON loaded. Review it before creating a delivery.')}catch{say('The selected file is not valid JSON.',true)}});
function normalizeCart(raw){const data=JSON.parse(raw);const items=Array.isArray(data)?data:Array.isArray(data.items)?data.items:Array.isArray(data.cart)?data.cart:null;if(!items||!items.length||items.length>100)throw Error('Cart must contain 1 to 100 items in an items or cart array.');const result=items.map((item,i)=>{if(!item||typeof item!=='object')throw Error('Item '+(i+1)+' is invalid.');const name=String(item.name||item.product_name||'').trim();const quantity=Number(item.quantity);if(!name||name.length>120||!Number.isFinite(quantity)||quantity<=0)throw Error('Each item needs a name and positive quantity.');return {name,quantity,unit:String(item.unit||'').slice(0,30)}});return {items:result,total:Number.isFinite(Number(data.total))?Number(data.total):null}}
function render(){if(!order){$('customerContent').innerHTML='<p>No demo delivery yet. Create one in Admin.</p>';$('partnerContent').innerHTML='<p>No assigned delivery yet.</p>';$('timeline').innerHTML='<p>No events yet.</p>';return}
$('customerContent').innerHTML=`<div class="summary"><strong>${escape(order.id)}</strong><span class="status">${escape(order.status)}</span></div><p><strong>Recipient:</strong> ${escape(order.customer)}</p><p><strong>Address:</strong> ${escape(order.address)}</p><p><strong>Cart:</strong> ${order.items.map(i=>escape(i.name)+' × '+i.quantity+' '+escape(i.unit)).join(', ')}</p><div class="code"><small>Handoff code · demo only</small><strong>${escape(order.code)}</strong></div><p class="note">In production this code is created on the server, sent to the customer, and never exposed to the delivery person.</p>`;
$('partnerContent').innerHTML=`<p><strong>${escape(order.id)}</strong> · ${escape(order.customer)} · ${escape(order.address)}</p><form id="verify"><label for="handoffCode">Code from customer</label><input id="handoffCode" type="text" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code" required><button type="submit" ${order.status==='Delivered'?'disabled':''}>Confirm handoff</button></form><p class="note">Production verification requires a server request, limited attempts, expiry, and an authenticated assigned delivery person.</p>`;
$('verify').addEventListener('submit',e=>{e.preventDefault();if(order.status==='Delivered')return;const typed=$('handoffCode').value.trim();if(typed!==order.code){say('Code does not match in this demo.',true);return}order.status='Delivered';order.events.push({label:'Delivered · code confirmed',at:new Date().toISOString()});save();say('Demo delivery confirmed. All three views now show the updated timeline.')});
$('timeline').innerHTML=`<ol class="timeline">${order.events.map(e=>`<li><strong>${escape(e.label)}</strong><time>${new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kolkata'}).format(new Date(e.at))} IST</time></li>`).join('')}</ol>`}
function save(){localStorage.setItem(key,JSON.stringify(order));render()}
$('create').addEventListener('click',()=>{try{const cart=normalizeCart($('cart').value),name=$('customerName').value.trim(),phone=$('customerPhone').value.trim(),address=$('address').value.trim(),source=$('sourceId').value.trim();if(!name||name.length>120||!address||address.length>500||!/^([+]?91[- ]?)?[6-9][0-9]{9}$/.test(phone))throw Error('Enter a customer name, address, and valid Indian mobile number.');if(order&&!confirm('Replace the current demo delivery in this browser?'))return;const bytes=new Uint32Array(1);crypto.getRandomValues(bytes);order={id:source||'DEMO-'+Date.now(),customer:name,phone,address,items:cart.items,total:cart.total,code:String(100000+bytes[0]%900000),status:'Awaiting handoff',events:[{label:'Delivery created by admin',at:new Date().toISOString()}]};save();say('Demo delivery created. Open Customer to see the code.');view('customer')}catch(e){say(e instanceof SyntaxError?'Cart is not valid JSON.':e.message,true)}});
render();
