'use strict';
const API='https://cserver.learnwithchampak.live/delivery/api/', $=id=>document.getElementById(id);
let adminPassword='',customerToken='',partnerToken='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function note(s,error=false){$('message').textContent=s;$('message').className=error?'error':'notice'}
async function request(action,method='GET',data=null,auth=''){const headers={'Content-Type':'application/json'};if(auth==='admin')headers['X-Admin-Password']=adminPassword;if(auth==='customer')headers.Authorization='Bearer '+customerToken;if(auth==='partner')headers.Authorization='Bearer '+partnerToken;const response=await fetch(API+'?action='+encodeURIComponent(action),{method,headers,body:data?JSON.stringify(data):undefined,cache:'no-store'});let result;try{result=await response.json()}catch{throw Error('Server response was invalid')}if(!response.ok)throw Error(result.error||'Request failed');return result}
function run(fn){return async(...args)=>{try{await fn(...args)}catch(e){note(e.message||'Request failed',true)}}}
document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==button.dataset.view);document.querySelectorAll('[data-view]').forEach(el=>el.setAttribute('aria-selected',String(el===button)));note('')});
$('file').onchange=run(async()=>{let f=$('file').files[0];if(!f)return;if(f.size>1024*1024)throw Error('JSON file must be under 1 MB');let raw=await f.text();JSON.parse(raw);$('cart').value=raw;note('Cart loaded for review. Import by Easy Mandi order ID.')});
$('adminLogin').onclick=run(async()=>{adminPassword=$('adminPassword').value;await loadAdmin();$('adminArea').hidden=false;$('adminLogout').hidden=false;$('adminPassword').value='';note('Admin access verified')});
$('adminLogout').onclick=()=>{adminPassword='';$('adminArea').hidden=true;$('adminLogout').hidden=true;$('adminOrders').replaceChildren();note('Admin locked')};
async function loadAdmin(){const data=await request('admin','POST',{operation:'list'},'admin');$('adminOrders').replaceChildren();for(const o of data.orders){const article=document.createElement('article');article.className='order';const title=document.createElement('h4');title.textContent=o.external_order_id+' · '+o.status;const details=document.createElement('p');details.textContent=o.customer_name+' · '+o.address_text;const select=document.createElement('select');const blank=document.createElement('option');blank.value='';blank.textContent='Assign delivery person';select.append(blank);for(const p of data.partners.filter(p=>p.active)){const option=document.createElement('option');option.value=p.id;option.textContent=p.name+' · '+p.mobile;select.append(option)}select.value=String(o.partner_id??'');const assign=document.createElement('button');assign.textContent='Assign';assign.onclick=run(async()=>{if(!select.value)throw Error('Select a delivery person');await request('admin','POST',{operation:'assign',id:Number(o.id),partner_id:Number(select.value)},'admin');note('Partner assigned');await loadAdmin()});article.append(title,details,select,assign);if(['assigned','picked_up','out_for_delivery'].includes(o.status)){const issue=document.createElement('button');issue.textContent='Issue customer code';issue.onclick=run(async()=>{const result=await request('admin','POST',{operation:'issue-code',id:Number(o.id)},'admin');const msg='Your delivery '+o.external_order_id+' handoff code is '+result.code+'. Give it to the delivery person only after receiving your order. This code expires in 24 hours.';const link=document.createElement('a');link.href='https://wa.me/91'+result.customer_mobile+'?text='+encodeURIComponent(msg);link.target='_blank';link.rel='noopener noreferrer';link.textContent='Send code to customer by WhatsApp';const p=document.createElement('p');p.textContent='Code: '+result.code+' · Send it now. It will not be shown again.';article.append(p,link);note('Code issued. Use the WhatsApp link to send it to the customer.')});article.append(issue)}$('adminOrders').append(article)}if(!data.orders.length)$('adminOrders').textContent='No deliveries yet.';$('adminNotifications').replaceChildren();for(const n of data.notifications||[]){let p=document.createElement('p');p.textContent=n.message+' · '+n.created_at;$('adminNotifications').append(p)}}
$('refreshAdmin').onclick=run(loadAdmin);
$('import').onclick=run(async()=>{let id=$('externalId').value.trim();if(!id)throw Error('Enter an Easy Mandi order ID');const result=await request('admin','POST',{operation:'import',source_app:'easymandi',external_order_id:id},'admin');note('Delivery '+result.id+(result.existing?' already exists':' created'));await loadAdmin()});
$('manualImport').onclick=run(async()=>{let cart;try{cart=JSON.parse($('cart').value)}catch{throw Error('Paste or upload valid cart JSON')}const result=await request('admin','POST',{operation:'manual-import',external_order_id:$('manualId').value.trim(),customer_name:$('manualName').value.trim(),customer_mobile:$('manualMobile').value.trim(),address:$('manualAddress').value.trim(),cart},'admin');note('Delivery '+result.id+(result.existing?' already exists':' created'));await loadAdmin()});
$('createPartner').onclick=run(async()=>{await request('admin','POST',{operation:'partner-create',name:$('partnerName').value.trim(),mobile:$('partnerMobile').value.trim(),password:$('partnerPassword').value},'admin');$('partnerPassword').value='';note('Partner account created');await loadAdmin()});
$('customerLogin').onclick=run(async()=>{customerToken=$('customerToken').value.trim();await loadCustomer();$('customerToken').value='';note('Customer deliveries loaded')});
$('customerLogout').onclick=()=>{customerToken='';$('customerOrders').replaceChildren();$('customerNotifications').replaceChildren();note('Customer token cleared')};
async function loadCustomer(){const data=await request('customer','GET',null,'customer');$('customerOrders').replaceChildren();for(const o of data.orders){let article=document.createElement('article');article.className='order';let title=document.createElement('h4');title.textContent=o.external_order_id+' · '+o.status;let p=document.createElement('p');p.textContent=o.address_text;article.append(title,p);if(['assigned','picked_up','out_for_delivery'].includes(o.status)){let hint=document.createElement('p');hint.textContent='The admin will send your handoff code. Give it to the delivery person only after receiving your order.';article.append(hint)}$('customerOrders').append(article)}if(!data.orders.length)$('customerOrders').textContent='No delivery orders linked to this account.';$('customerNotifications').replaceChildren();for(const n of data.notifications){let p=document.createElement('p');p.textContent=n.message+' · '+n.created_at;$('customerNotifications').append(p)}}
$('loginPartner').onclick=run(async()=>{const data=await request('partner-login','POST',{mobile:$('loginMobile').value.trim(),password:$('loginPassword').value});partnerToken=data.token;$('loginPassword').value='';$('partnerLogin').hidden=true;$('partnerArea').hidden=false;await loadPartner();note('Signed in')});
$('logoutPartner').onclick=()=>{partnerToken='';$('partnerArea').hidden=true;$('partnerLogin').hidden=false;$('partnerOrders').replaceChildren();note('Signed out')};
$('refreshPartner').onclick=run(loadPartner);
async function loadPartner(){const data=await request('partner','GET',null,'partner');$('partnerOrders').replaceChildren();for(const o of data.orders){let article=document.createElement('article');article.className='order';let h=document.createElement('h4');h.textContent=o.external_order_id+' · '+o.status;let p=document.createElement('p');p.textContent=o.customer_name+' · '+o.address_text;article.append(h,p);const next={assigned:'picked_up',picked_up:'out_for_delivery'}[o.status];if(next){let button=document.createElement('button');button.textContent='Mark '+next.replaceAll('_',' ');button.onclick=run(async()=>{await request('partner','POST',{operation:'status',id:Number(o.id),status:next},'partner');await loadPartner();note('Status updated')});article.append(button)}if(o.status==='out_for_delivery'){let input=document.createElement('input');input.placeholder='Six-digit code from customer';input.inputMode='numeric';input.maxLength=6;let button=document.createElement('button');button.textContent='Confirm handoff';button.onclick=run(async()=>{await request('partner','POST',{operation:'confirm',id:Number(o.id),code:input.value.trim()},'partner');input.value='';await loadPartner();note('Delivery confirmed; notifications recorded')});article.append(input,button)}$('partnerOrders').append(article)}if(!data.orders.length)$('partnerOrders').textContent='No assigned jobs.';$('partnerNotifications').replaceChildren();for(const n of data.notifications){let p=document.createElement('p');p.textContent=n.message+' · '+n.created_at;$('partnerNotifications').append(p)}}
